# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 738a2fb4916bd44e36bcad763c565554411b8e4717fcb3c711cf592cd5db6ae966129caded0945a0e6613618e3ccae7c6014bf2a78aa17fb721082824c457e2c

test:
  secret_key_base: ff9576f28f8c2b0d51e40125bd5a21e068eb20967eb9969333941ff116e62022d42dd3fc225af97bd2a20e3cee29cf212bdeca5fa6e4572aa218e5df57c07d5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
